/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AuthorIndexRouteImport } from './routes/author.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthorProfileRouteImport } from './routes/author.profile'
import { Route as AuthorLoginRouteImport } from './routes/author.login'
import { Route as AuthorCommentsRouteImport } from './routes/author.comments'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginGateRouteImport } from './routes/admin.login-gate'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminAuthorsRouteImport } from './routes/admin.authors'
import { Route as AuthorPostsIndexRouteImport } from './routes/author.posts.index'
import { Route as AdminRestaurantsIndexRouteImport } from './routes/admin.restaurants.index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as BlogAuthorSlugRouteImport } from './routes/blog.author.$slug'
import { Route as AuthorPostsNewRouteImport } from './routes/author.posts.new'
import { Route as AdminRestaurantsNewRouteImport } from './routes/admin.restaurants.new'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AuthorPostsIdEditRouteImport } from './routes/author.posts.$id.edit'
import { Route as AdminRestaurantsIdEditRouteImport } from './routes/admin.restaurants.$id.edit'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthorProfileRoute = AuthorProfileRouteImport.update({
  id: '/author/profile',
  path: '/author/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorLoginRoute = AuthorLoginRouteImport.update({
  id: '/author/login',
  path: '/author/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorCommentsRoute = AuthorCommentsRouteImport.update({
  id: '/author/comments',
  path: '/author/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginGateRoute = AdminLoginGateRouteImport.update({
  id: '/admin/login-gate',
  path: '/admin/login-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/admin/authors',
  path: '/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorPostsIndexRoute = AuthorPostsIndexRouteImport.update({
  id: '/author/posts/',
  path: '/author/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsIndexRoute = AdminRestaurantsIndexRouteImport.update({
  id: '/admin/restaurants/',
  path: '/admin/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/admin/posts/',
  path: '/admin/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAuthorSlugRoute = BlogAuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthorPostsNewRoute = AuthorPostsNewRouteImport.update({
  id: '/author/posts/new',
  path: '/author/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsNewRoute = AdminRestaurantsNewRouteImport.update({
  id: '/admin/restaurants/new',
  path: '/admin/restaurants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorPostsIdEditRoute = AuthorPostsIdEditRouteImport.update({
  id: '/author/posts/$id/edit',
  path: '/author/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsIdEditRoute = AdminRestaurantsIdEditRouteImport.update({
  id: '/admin/restaurants/$id/edit',
  path: '/admin/restaurants/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/admin/posts/$id/edit',
  path: '/admin/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login-gate': typeof AdminLoginGateRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/team': typeof AdminTeamRoute
  '/author/comments': typeof AuthorCommentsRoute
  '/author/login': typeof AuthorLoginRoute
  '/author/profile': typeof AuthorProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/author/': typeof AuthorIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/restaurants/new': typeof AdminRestaurantsNewRoute
  '/author/posts/new': typeof AuthorPostsNewRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/restaurants/': typeof AdminRestaurantsIndexRoute
  '/author/posts/': typeof AuthorPostsIndexRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/admin/restaurants/$id/edit': typeof AdminRestaurantsIdEditRoute
  '/author/posts/$id/edit': typeof AuthorPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login-gate': typeof AdminLoginGateRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/team': typeof AdminTeamRoute
  '/author/comments': typeof AuthorCommentsRoute
  '/author/login': typeof AuthorLoginRoute
  '/author/profile': typeof AuthorProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/author': typeof AuthorIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/restaurants/new': typeof AdminRestaurantsNewRoute
  '/author/posts/new': typeof AuthorPostsNewRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/restaurants': typeof AdminRestaurantsIndexRoute
  '/author/posts': typeof AuthorPostsIndexRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/admin/restaurants/$id/edit': typeof AdminRestaurantsIdEditRoute
  '/author/posts/$id/edit': typeof AuthorPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/faq': typeof FaqRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login-gate': typeof AdminLoginGateRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/team': typeof AdminTeamRoute
  '/author/comments': typeof AuthorCommentsRoute
  '/author/login': typeof AuthorLoginRoute
  '/author/profile': typeof AuthorProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/author/': typeof AuthorIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/restaurants/new': typeof AdminRestaurantsNewRoute
  '/author/posts/new': typeof AuthorPostsNewRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/restaurants/': typeof AdminRestaurantsIndexRoute
  '/author/posts/': typeof AuthorPostsIndexRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/admin/restaurants/$id/edit': typeof AdminRestaurantsIdEditRoute
  '/author/posts/$id/edit': typeof AuthorPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/faq'
    | '/partner'
    | '/privacy'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/team'
    | '/admin/authors'
    | '/admin/comments'
    | '/admin/jobs'
    | '/admin/login-gate'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/author/comments'
    | '/author/login'
    | '/author/profile'
    | '/blog/$slug'
    | '/admin/'
    | '/author/'
    | '/blog/'
    | '/admin/posts/new'
    | '/admin/restaurants/new'
    | '/author/posts/new'
    | '/blog/author/$slug'
    | '/admin/posts/'
    | '/admin/restaurants/'
    | '/author/posts/'
    | '/admin/posts/$id/edit'
    | '/admin/restaurants/$id/edit'
    | '/author/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/auth'
    | '/careers'
    | '/faq'
    | '/partner'
    | '/privacy'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/team'
    | '/admin/authors'
    | '/admin/comments'
    | '/admin/jobs'
    | '/admin/login-gate'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/author/comments'
    | '/author/login'
    | '/author/profile'
    | '/blog/$slug'
    | '/admin'
    | '/author'
    | '/blog'
    | '/admin/posts/new'
    | '/admin/restaurants/new'
    | '/author/posts/new'
    | '/blog/author/$slug'
    | '/admin/posts'
    | '/admin/restaurants'
    | '/author/posts'
    | '/admin/posts/$id/edit'
    | '/admin/restaurants/$id/edit'
    | '/author/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/faq'
    | '/partner'
    | '/privacy'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/team'
    | '/admin/authors'
    | '/admin/comments'
    | '/admin/jobs'
    | '/admin/login-gate'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/author/comments'
    | '/author/login'
    | '/author/profile'
    | '/blog/$slug'
    | '/admin/'
    | '/author/'
    | '/blog/'
    | '/admin/posts/new'
    | '/admin/restaurants/new'
    | '/author/posts/new'
    | '/blog/author/$slug'
    | '/admin/posts/'
    | '/admin/restaurants/'
    | '/author/posts/'
    | '/admin/posts/$id/edit'
    | '/admin/restaurants/$id/edit'
    | '/author/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  FaqRoute: typeof FaqRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginGateRoute: typeof AdminLoginGateRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AuthorCommentsRoute: typeof AuthorCommentsRoute
  AuthorLoginRoute: typeof AuthorLoginRoute
  AuthorProfileRoute: typeof AuthorProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminRestaurantsNewRoute: typeof AdminRestaurantsNewRoute
  AuthorPostsNewRoute: typeof AuthorPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminRestaurantsIndexRoute: typeof AdminRestaurantsIndexRoute
  AuthorPostsIndexRoute: typeof AuthorPostsIndexRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
  AdminRestaurantsIdEditRoute: typeof AdminRestaurantsIdEditRoute
  AuthorPostsIdEditRoute: typeof AuthorPostsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/author/profile': {
      id: '/author/profile'
      path: '/author/profile'
      fullPath: '/author/profile'
      preLoaderRoute: typeof AuthorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/login': {
      id: '/author/login'
      path: '/author/login'
      fullPath: '/author/login'
      preLoaderRoute: typeof AuthorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/comments': {
      id: '/author/comments'
      path: '/author/comments'
      fullPath: '/author/comments'
      preLoaderRoute: typeof AuthorCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login-gate': {
      id: '/admin/login-gate'
      path: '/admin/login-gate'
      fullPath: '/admin/login-gate'
      preLoaderRoute: typeof AdminLoginGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/admin/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/posts/': {
      id: '/author/posts/'
      path: '/author/posts'
      fullPath: '/author/posts/'
      preLoaderRoute: typeof AuthorPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants/': {
      id: '/admin/restaurants/'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants/'
      preLoaderRoute: typeof AdminRestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/author/$slug': {
      id: '/blog/author/$slug'
      path: '/author/$slug'
      fullPath: '/blog/author/$slug'
      preLoaderRoute: typeof BlogAuthorSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/author/posts/new': {
      id: '/author/posts/new'
      path: '/author/posts/new'
      fullPath: '/author/posts/new'
      preLoaderRoute: typeof AuthorPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants/new': {
      id: '/admin/restaurants/new'
      path: '/admin/restaurants/new'
      fullPath: '/admin/restaurants/new'
      preLoaderRoute: typeof AdminRestaurantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/posts/$id/edit': {
      id: '/author/posts/$id/edit'
      path: '/author/posts/$id/edit'
      fullPath: '/author/posts/$id/edit'
      preLoaderRoute: typeof AuthorPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants/$id/edit': {
      id: '/admin/restaurants/$id/edit'
      path: '/admin/restaurants/$id/edit'
      fullPath: '/admin/restaurants/$id/edit'
      preLoaderRoute: typeof AdminRestaurantsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/admin/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogAuthorSlugRoute: typeof BlogAuthorSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogAuthorSlugRoute: BlogAuthorSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  FaqRoute: FaqRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  RestaurantsRoute: RestaurantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginGateRoute: AdminLoginGateRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTeamRoute: AdminTeamRoute,
  AuthorCommentsRoute: AuthorCommentsRoute,
  AuthorLoginRoute: AuthorLoginRoute,
  AuthorProfileRoute: AuthorProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminRestaurantsNewRoute: AdminRestaurantsNewRoute,
  AuthorPostsNewRoute: AuthorPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminRestaurantsIndexRoute: AdminRestaurantsIndexRoute,
  AuthorPostsIndexRoute: AuthorPostsIndexRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
  AdminRestaurantsIdEditRoute: AdminRestaurantsIdEditRoute,
  AuthorPostsIdEditRoute: AuthorPostsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
