ALTER TABLE public.blog_settings
  ADD COLUMN IF NOT EXISTS site_name text NOT NULL DEFAULT 'Zaaou',
  ADD COLUMN IF NOT EXISTS site_tagline text NOT NULL DEFAULT 'Food delivery, reimagined.',
  ADD COLUMN IF NOT EXISTS site_logo_url text,
  ADD COLUMN IF NOT EXISTS contact_phone_primary text NOT NULL DEFAULT '+977 970-5047000',
  ADD COLUMN IF NOT EXISTS contact_phone_secondary text NOT NULL DEFAULT '+977 982-0757417',
  ADD COLUMN IF NOT EXISTS contact_email text NOT NULL DEFAULT 'info@zaaoufoods.com',
  ADD COLUMN IF NOT EXISTS contact_address text NOT NULL DEFAULT 'Itahari, Nepal',
  ADD COLUMN IF NOT EXISTS contact_whatsapp text NOT NULL DEFAULT '+9779705047000',
  ADD COLUMN IF NOT EXISTS social_facebook_url text,
  ADD COLUMN IF NOT EXISTS social_instagram_url text,
  ADD COLUMN IF NOT EXISTS social_tiktok_url text,
  ADD COLUMN IF NOT EXISTS social_youtube_url text,
  ADD COLUMN IF NOT EXISTS social_twitter_url text,
  ADD COLUMN IF NOT EXISTS social_linkedin_url text,
  ADD COLUMN IF NOT EXISTS seo_default_title text NOT NULL DEFAULT 'Zaaou — Food delivery, reimagined.',
  ADD COLUMN IF NOT EXISTS seo_default_description text NOT NULL DEFAULT 'Order from your favorite restaurants in Itahari with Zaaou. Fast delivery, great prices.',
  ADD COLUMN IF NOT EXISTS seo_default_og_image_url text,
  ADD COLUMN IF NOT EXISTS maintenance_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS maintenance_message text NOT NULL DEFAULT 'We''ll be right back. Thanks for your patience!';